<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <Title>Beskar.Mqtt.Server</Title>
      <Description>High-performance, low-allocation MQTT broker/server support for v3.1.1 and v5.0 over any transport.</Description>
      <IsPackable>true</IsPackable>
   </PropertyGroup>

   <ItemGroup>
      <ProjectReference Include="..\Beskar.Mqtt.Client\Beskar.Mqtt.Client.csproj" />
      <ProjectReference Include="..\Beskar.Mqtt.Common\Beskar.Mqtt.Common.csproj" />
      <ProjectReference Include="..\Beskar.Mqtt.Protocol\Beskar.Mqtt.Protocol.csproj" />
   </ItemGroup>
   
   <ItemGroup>
      <InternalsVisibleTo Include="Beskar.Mqtt.Common.Tests" />
      <InternalsVisibleTo Include="Beskar.Mqtt.Integration.Tests" />
      <InternalsVisibleTo Include="Beskar.Mqtt.AutoReconnectStressTest" />
   </ItemGroup>

</Project>
