<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
   </PropertyGroup>

   <ItemGroup>
     <ProjectReference Include="..\Beskar.Networking.Abstractions\Beskar.Networking.Abstractions.csproj" />
     <ProjectReference Include="..\Beskar.Networking.Transports.Common\Beskar.Networking.Transports.Common.csproj" />
   </ItemGroup>

</Project>
