<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <Title>Beskar.Mqtt.Client</Title>
      <Description>Lightweight and efficient MQTT client supporting v3.1.1 and v5.0 over any transport.</Description>
      <IsPackable>true</IsPackable>
   </PropertyGroup>

   <ItemGroup>
      <ProjectReference Include="..\..\Beskar.Networking.Abstractions\Beskar.Networking.Abstractions.csproj" />
      <ProjectReference Include="..\..\Beskar.Networking.Transports.Quic\Beskar.Networking.Transports.Quic.csproj" />
      <ProjectReference Include="..\..\Beskar.Networking.Transports.Ws\Beskar.Networking.Transports.Ws.csproj" />
      <ProjectReference Include="..\Beskar.Mqtt.Common\Beskar.Mqtt.Common.csproj" />
   </ItemGroup>

   <ItemGroup>
      <InternalsVisibleTo Include="Beskar.Mqtt.Common.Tests" />
   </ItemGroup>

</Project>
