<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <Title>Beskar.Mqtt.Common</Title>
      <Description>Common types and utilities for Beskar.Mqtt.</Description>
      <IsPackable>true</IsPackable>
   </PropertyGroup>

   <ItemGroup>
     <ProjectReference Include="..\..\Utilities\Beskar.Utilities.Tracing\Beskar.Utilities.Tracing.csproj" />
     <ProjectReference Include="..\Beskar.Mqtt.Protocol\Beskar.Mqtt.Protocol.csproj" />
     <ProjectReference Include="..\..\Beskar.Networking.Abstractions\Beskar.Networking.Abstractions.csproj" />
     <ProjectReference Include="..\Beskar.Mqtt.Common.Generators\Beskar.Mqtt.Common.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
   </ItemGroup>

   <ItemGroup>
     <PackageReference Include="Beskar.Memory" />
   </ItemGroup>

   <ItemGroup>
     <InternalsVisibleTo Include="Beskar.Mqtt.Client" />
     <InternalsVisibleTo Include="Beskar.Mqtt.Common.Tests" />
   </ItemGroup>

   <ItemGroup>
     <Folder Include="Builders\Publishing\" />
   </ItemGroup>

</Project>
