<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
   </PropertyGroup>

   <ItemGroup>
     <ProjectReference Include="..\..\Utilities\Beskar.Utilities.Tracing\Beskar.Utilities.Tracing.csproj" />
     <ProjectReference Include="..\Beskar.Mqtt.Protocol\Beskar.Mqtt.Protocol.csproj" />
   </ItemGroup>

   <ItemGroup>
     <PackageReference Include="Beskar.Memory" />
   </ItemGroup>

   <ItemGroup>
     <Folder Include="Builders\Publishing\" />
     <Folder Include="Encoders\Version5\" />
   </ItemGroup>

</Project>
