<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
      <IsPackable>false</IsPackable>
   </PropertyGroup>

   <ItemGroup>
      <ProjectReference Include="..\..\..\Beskar.Networking.Abstractions\Beskar.Networking.Abstractions.csproj"/>
      <ProjectReference Include="..\..\..\Common\Beskar.Networking.Protocol\Beskar.Networking.Protocol.csproj"/>
      <ProjectReference Include="..\..\..\Common\Beskar.Networking.Resilient.Client\Beskar.Networking.Resilient.Client.csproj"/>
      <ProjectReference Include="..\Beskar.Resilient.Chat.Common\Beskar.Resilient.Chat.Common.csproj"/>
   </ItemGroup>

</Project>
