<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <IsPackable>false</IsPackable>
   </PropertyGroup>

   <ItemGroup>
      <ProjectReference Include="..\..\..\Mqtt\Beskar.Mqtt.Server\Beskar.Mqtt.Server.csproj" />
      <ProjectReference Include="..\..\..\Mqtt\Beskar.Mqtt.Client\Beskar.Mqtt.Client.csproj" />
      <ProjectReference Include="..\..\..\Mqtt\Beskar.Mqtt.Common.Generators\Beskar.Mqtt.Common.Generators.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
      <ProjectReference Include="..\..\..\Utilities\Beskar.Utilities.Tracing\Beskar.Utilities.Tracing.csproj" />
   </ItemGroup>

</Project>
