<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <Title>Beskar.Networking.Transports.Udp</Title>
      <Description>Underlying UDP Implementation for Beskar.Networking.</Description>
      <IsPackable>true</IsPackable>
   </PropertyGroup>

   <ItemGroup>
      <ProjectReference Include="..\Beskar.Networking.Abstractions\Beskar.Networking.Abstractions.csproj" />
      <ProjectReference Include="..\Beskar.Networking.Transports.Common\Beskar.Networking.Transports.Common.csproj" />
      <ProjectReference Include="..\Utilities\Beskar.Utilities.Tracing\Beskar.Utilities.Tracing.csproj" />
   </ItemGroup>

</Project>
