<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <Title>Beskar.Utilities.Tracing</Title>
      <Description>Tracing, performance profiling, and observability helpers for Beskar.</Description>
      <IsPackable>true</IsPackable>
   </PropertyGroup>

   <ItemGroup>
     <ProjectReference Include="..\Beskar.Utilities.Console\Beskar.Utilities.Console.csproj" />
   </ItemGroup>

   <ItemGroup>
     <PackageReference Include="Beskar.Memory" />
   </ItemGroup>

</Project>
