<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <Title>Beskar.Networking.Abstractions</Title>
      <Description>Abstractions and core interfaces for Beskar.Networking.</Description>
      <IsPackable>true</IsPackable>
   </PropertyGroup>

   <ItemGroup>
     <PackageReference Include="Beskar.Memory" />
     <ProjectReference Include="..\Utilities\Beskar.Utilities.Tracing\Beskar.Utilities.Tracing.csproj" />
   </ItemGroup>

</Project>
