<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
   </PropertyGroup>

   <ItemGroup>
     <Folder Include="Validators\Version5\" />
   </ItemGroup>

   <ItemGroup>
     <PackageReference Include="Beskar.Memory" />
     <PackageReference Include="Beskar.Memory.Code.EnumGenerator" />
   </ItemGroup>

</Project>
