<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <Title>Beskar.Mqtt.Protocol</Title>
      <Description>MQTT protocol parsing, packets, and framing logic.</Description>
      <IsPackable>true</IsPackable>
   </PropertyGroup>

   <ItemGroup>
     <Folder Include="Validators\Version5\" />
   </ItemGroup>

   <ItemGroup>
     <PackageReference Include="Beskar.Memory" />
     <PackageReference Include="Beskar.Memory.Code.EnumGenerator" />
   </ItemGroup>

</Project>
