using System.Text;
using Beskar.Memory.Code;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Beskar.Networking.Protocol.Generators;

public partial class FramingProtocolGenerator
{
   private static void GenerateSourceForType(SourceProductionContext spc, GeneratedTypeModel model)
   {
      if (model.IsErrorTypeNotPartial)
      {
         spc.ReportDiagnostic(Diagnostic.Create(
            TargetTypeMustBePartial,
            model.TypeLocation.ToLocation(),
            model.TypeName));
         return;
      }

      Span<char> initialBuffer = stackalloc char[512];
      var writer = new CodeTextWriter(initialBuffer, stackalloc char[64]);

      try
      {
         writer.WriteLine("// <auto-generated/>");
         writer.WriteLine("#nullable enable");
         writer.WriteLine("#pragma warning disable CS0162 // Unreachable code detected");
         writer.WriteLine("using System;");
         writer.WriteLine("using System.Buffers;");
         writer.WriteLine("using System.Buffers.Binary;");
         writer.WriteLine("using Beskar.Memory.Flags;");
         writer.WriteLine("using Beskar.Networking.Protocol.Utilities;");
         writer.WriteLine();

         var hasNamespace = !string.IsNullOrEmpty(model.NamespaceName);
         if (hasNamespace)
         {
            writer.WriteLine("namespace " + model.NamespaceName);
            writer.OpenBody();
         }

         foreach (var type in model.NestingTypes)
         {
            writer.WriteLine("partial " + type.TypeKind + " " + type.Name);
            writer.OpenBody();
         }

         writer.WriteLine("partial " + model.TypeKind + " " + model.TypeName);
         writer.OpenBody();

         // Partial properties implementation
         foreach (var prop in model.Properties)
         {
            if (prop.IsPartial)
            {
               if (prop.AttributeKind == ProtocolAttributeKind.MagicBytes)
               {
                  writer.WriteLine("public partial bool " + prop.PropertyName + " => true;");
               }
               else
               {
                  writer.WriteLine("public partial " + prop.PropertyType + " " + prop.PropertyName + " => default!;");
               }
               writer.WriteLine();
            }
         }

         RenderGetEncodedLength(ref writer, model);
         RenderTryWrite(ref writer, model);
         RenderTryRead(ref writer, model);
         RenderWriteTo(ref writer, model);

         writer.CloseBody(); // target type

         for (var i = 0; i < model.NestingTypes.Length; i++) writer.CloseBody();

         if (hasNamespace) writer.CloseBody();

         var typePrefix = model.NestingTypes.Length > 0
            ? string.Join("_", model.NestingTypes.Select(t => t.Name)) + "_" + model.TypeName
            : model.TypeName;

         var hintName = $"{typePrefix}.Framing.g.cs";
         spc.AddSource(hintName, SourceText.From(writer.ToString(), Encoding.UTF8));
      }
      finally
      {
         writer.Dispose();
      }
   }

   private static void RenderGetEncodedLength(ref CodeTextWriter writer, GeneratedTypeModel model)
   {
      writer.WriteLine("public readonly int GetEncodedLength()");
      writer.OpenBody();
      writer.WriteLine("int length = 0;");

      foreach (var prop in model.Properties)
      {
         switch (prop.AttributeKind)
         {
            case ProtocolAttributeKind.MagicBytes:
               writer.WriteLine("length += " + prop.MagicBytes.Length + ";");
               break;
            case ProtocolAttributeKind.VersionField:
               writer.WriteLine("length += 1;");
               break;
            case ProtocolAttributeKind.ProtocolField:
               writer.WriteLine("length += System.Runtime.CompilerServices.Unsafe.SizeOf<" + prop.PropertyType + ">();");
               break;
            case ProtocolAttributeKind.FlagsField:
               if (prop.PropertyType.Contains("PackedBools16")) writer.WriteLine("length += 2;");
               else if (prop.PropertyType.Contains("PackedBools32")) writer.WriteLine("length += 4;");
               else if (prop.PropertyType.Contains("PackedBools64")) writer.WriteLine("length += 8;");
               else if (prop.PropertyType.Contains("PackedBools8")) writer.WriteLine("length += 1;");
               else writer.WriteLine("length += System.Runtime.CompilerServices.Unsafe.SizeOf<" + prop.PropertyType + ">();");
               break;
            case ProtocolAttributeKind.VarNumberField:
               writer.WriteLine("length += VarNumber.GetEncodedLength(" + prop.PropertyName + ");");
               break;
            case ProtocolAttributeKind.ByteSequenceField:
               writer.WriteLine("length += (int)" + prop.PropertyName + ".Length;");
               break;
         }
      }

      writer.WriteLine("return length;");
      writer.CloseBody();
      writer.WriteLine();
   }

   private static void RenderTryWrite(ref CodeTextWriter writer, GeneratedTypeModel model)
   {
      writer.WriteLine("public readonly bool TryWrite(Span<byte> destination, out int bytesWritten)");
      writer.OpenBody();
      writer.WriteLine("bytesWritten = 0;");
      writer.WriteLine("int totalRequired = GetEncodedLength();");
      writer.WriteLine("if (destination.Length < totalRequired) return false;");
      writer.WriteLine();

      foreach (var prop in model.Properties)
      {
         switch (prop.AttributeKind)
         {
            case ProtocolAttributeKind.MagicBytes:
               for (int i = 0; i < prop.MagicBytes.Length; i++)
               {
                  writer.WriteLine("destination[bytesWritten++] = 0x" + prop.MagicBytes[i].ToString("X2") + ";");
               }
               break;
            case ProtocolAttributeKind.VersionField:
               writer.WriteLine("destination[bytesWritten++] = " + prop.PropertyName + ";");
               break;
            case ProtocolAttributeKind.ProtocolField:
               writer.WriteLine("BinaryPrimitives.WriteUInt16BigEndian(destination.Slice(bytesWritten), Convert.ToUInt16(" + prop.PropertyName + "));");
               writer.WriteLine("bytesWritten += 2;");
               break;
            case ProtocolAttributeKind.FlagsField:
               writer.WriteLine("var flagsCopy_" + prop.PropertyName + " = " + prop.PropertyName + ";");
               writer.WriteLine("BinaryPrimitives.WriteUInt16BigEndian(destination.Slice(bytesWritten), System.Runtime.CompilerServices.Unsafe.As<" + prop.PropertyType + ", ushort>(ref flagsCopy_" + prop.PropertyName + "));");
               writer.WriteLine("bytesWritten += 2;");
               break;
            case ProtocolAttributeKind.VarNumberField:
               writer.WriteLine("bytesWritten += VarNumber.Write(destination.Slice(bytesWritten), " + prop.PropertyName + ");");
               break;
            case ProtocolAttributeKind.ByteSequenceField:
               writer.WriteLine(prop.PropertyName + ".CopyTo(destination.Slice(bytesWritten));");
               writer.WriteLine("bytesWritten += (int)" + prop.PropertyName + ".Length;");
               break;
         }
      }

      writer.WriteLine("return true;");
      writer.CloseBody();
      writer.WriteLine();
   }

   private static void RenderTryRead(ref CodeTextWriter writer, GeneratedTypeModel model)
   {
      writer.WriteLine("public static bool TryRead(ref SequenceReader<byte> reader, out " + model.TypeName + " result)");
      writer.OpenBody();
      writer.WriteLine("result = default;");
      writer.WriteLine("var pkt = new " + model.TypeName + "();");

      foreach (var prop in model.Properties)
      {
         switch (prop.AttributeKind)
         {
            case ProtocolAttributeKind.MagicBytes:
               for (int i = 0; i < prop.MagicBytes.Length; i++)
               {
                  writer.WriteLine("if (!reader.TryRead(out byte b" + i + ") || b" + i + " != 0x" + prop.MagicBytes[i].ToString("X2") + ") return false;");
               }
               break;
            case ProtocolAttributeKind.VersionField:
               writer.WriteLine("if (!reader.TryRead(out byte ver)) return false;");
               writer.WriteLine("pkt." + prop.PropertyName + " = ver;");
               break;
            case ProtocolAttributeKind.ProtocolField:
               writer.WriteLine("if (!reader.TryReadBigEndian(out short pTypeRaw)) return false;");
               writer.WriteLine("pkt." + prop.PropertyName + " = (" + prop.PropertyType + ")(ushort)pTypeRaw;");
               break;
            case ProtocolAttributeKind.FlagsField:
               writer.WriteLine("if (!reader.TryReadBigEndian(out short flagsRaw)) return false;");
               writer.WriteLine("ushort flagsU16 = (ushort)flagsRaw;");
               writer.WriteLine("pkt." + prop.PropertyName + " = System.Runtime.CompilerServices.Unsafe.As<ushort, " + prop.PropertyType + ">(ref flagsU16);");
               break;
            case ProtocolAttributeKind.VarNumberField:
               writer.WriteLine("if (!VarNumber.TryRead(ref reader, out " + prop.PropertyType + " varVal_" + prop.PropertyName + ")) return false;");
               writer.WriteLine("pkt." + prop.PropertyName + " = varVal_" + prop.PropertyName + ";");
               break;
            case ProtocolAttributeKind.ByteSequenceField:
               if (!string.IsNullOrEmpty(prop.LengthPropertyName))
               {
                  var lenProp = prop.LengthPropertyName!;
                  writer.WriteLine("int seqLen = pkt." + lenProp + ";");
               }
               else
               {
                  writer.WriteLine("int seqLen = (int)(reader.Length - reader.Consumed);");
               }
               writer.WriteLine("if (reader.UnreadSequence.Length < seqLen) return false;");
               writer.WriteLine("var seq = reader.UnreadSequence.Slice(0, seqLen);");
               writer.WriteLine("reader.Advance(seqLen);");
               writer.WriteLine("pkt." + prop.PropertyName + " = seq;");
               break;
         }
      }

      writer.WriteLine("result = pkt;");
      writer.WriteLine("return true;");
      writer.CloseBody();
      writer.WriteLine();
   }

   private static void RenderWriteTo(ref CodeTextWriter writer, GeneratedTypeModel model)
   {
      writer.WriteLine("public readonly void WriteTo(IBufferWriter<byte> writer)");
      writer.OpenBody();
      writer.WriteLine("int size = GetEncodedLength();");
      writer.WriteLine("Span<byte> span = writer.GetSpan(size);");
      writer.WriteLine("TryWrite(span, out int written);");
      writer.WriteLine("writer.Advance(written);");
      writer.CloseBody();
   }
}
