<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <OutputType>Exe</OutputType>
   </PropertyGroup>

   <ItemGroup>
      <PackageReference Include="TUnit"/>
   </ItemGroup>

   <ItemGroup>
      <ProjectReference Include="..\Beskar.Mqtt.Common\Beskar.Mqtt.Common.csproj"/>
      <ProjectReference Include="..\Beskar.Mqtt.Server\Beskar.Mqtt.Server.csproj"/>
      <ProjectReference Include="..\Beskar.Mqtt.Client\Beskar.Mqtt.Client.csproj"/>
   </ItemGroup>

</Project>
