<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <OutputType>Exe</OutputType>
      <IsPackable>false</IsPackable>
      <!--      <TargetFramework>net11.0</TargetFramework>-->
      <!--      <LangVersion>preview</LangVersion>-->
      <!--      <Features>$(Features);runtime-async=on</Features>-->
   </PropertyGroup>

   <ItemGroup>
      <PackageReference Include="BenchmarkDotNet"/>
   </ItemGroup>

</Project>
