<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
   </PropertyGroup>

   <ItemGroup>
     <PackageReference Include="Beskar.Memory.Code.EnumGenerator" />
     <PackageReference Include="Beskar.Memory.Code.PacketGenerator" />
     <PackageReference Include="Beskar.Memory.Serialization" />
   </ItemGroup>

   <ItemGroup>
     <Folder Include="Registries\" />
   </ItemGroup>

   <ItemGroup>
     <ProjectReference Include="..\..\Common\Beskar.Networking.Common\Beskar.Networking.Common.csproj" />
   </ItemGroup>

</Project>
