namespace Beskar.Networking.Abstractions.Backoffs;

/// <summary>
/// Specifies the randomized jitter strategy applied to a backoff policy.
/// </summary>
public enum JitterMode
{
   /// <summary>
   /// Uniform random delay between 0 and the base delay generated by the inner backoff policy.
   /// </summary>
   Full,

   /// <summary>
   /// Half constant delay and half uniform random delay (baseDelay / 2 + random(0, baseDelay / 2)).
   /// </summary>
   Equal,

   /// <summary>
   /// Applies a proportional random variance around the base delay using a jitter factor (e.g., +/- 20%).
   /// </summary>
   Proportional
}
