<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <TargetFramework>net10.0</TargetFramework>
      <ImplicitUsings>enable</ImplicitUsings>
      <Nullable>enable</Nullable>
   </PropertyGroup>

   <PropertyGroup>
      <Title>Beskar.Utilities.Console</Title>
      <Description>Console and logging utility helpers for Beskar.</Description>
      <IsPackable>true</IsPackable>
   </PropertyGroup>

</Project>
